language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ../project

script:
  - make
  - ./runUnitTests
  - perf/perf

notifications:
  recipients:
    - geetasen@gmail.com
  email:
    on_success: change
    on_failure: always