language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ../src

script: make

notifications:
  recipients:
    - geetasen@gmail.com
  email:
    on_success: change
    on_failure: always