language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ../project

script: make && make test

notifications:
  recipients:
    - geetasen@gmail.com
  email:
    on_success: change
    on_failure: always